### PR TITLE
Merge Logstash 1.4.4 changes to our repo

### PR DESCRIPTION
**Pull request by ikoniaris**
What the title says. Our current code is still Logstash 1.4.1 (plus our improvements -- see closed PRs). I've merged the latest code from the 1.4.4 version (the latest 1.4.x) so we're up to date. FYI I've already built a package with 1.4.4 and we're successfully using it for a long time on our boxes, I've just forgotten to create a PR. FYI, the package already exists internally as 1.4.4-1-4c62d38, no need to built a new package, etc, after this is merged. This is mostly to tidy things up and sync our forks.

### CODE REVIEW

**Comment by Qmando** [comment]
shipit

**Review by danielpops — APPROVED** [review]
glanced through it. lgtm, especially as there were no conflicts.

**Comment by ikoniaris** [comment]
@ecanzonieri I'm going to merge this PR.

**Comment by ikoniaris** [comment]
As I explained above, we don't have to do anything else as the package has already been built and exists in our package repo.

**Pull request merged**
